env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  object-curly-newline:
  - 0
  - ImportDeclaration: never
  no-restricted-syntax:
  - 0
  - selector: ForOfStatement
